config/routes.rb
Rails.application.routes.draw do

  get 'xgc/:address/:nomor' => 'events#xgc'  

  resources :kartus
  get 'saldo/:nomor' => 'kartus#show_saldo' , as: :show_saldo
  put 'xsc/:nomor' => 'kartus#xsc' , as: :xsc
  put 'add_saldo/:nomor' => 'kartus#add_saldo' 

  resources :games
  put 'games/:id/:address' => 'games#set_game_mac' , as: :set_game_mac

  resources :macs
  get 'get_game_id/:address' => 'macs#get_id' 

  root 'pages#main'

end

app/models/kartu.rb
class Kartu < ActiveRecord::Base
end

app/controllers/kartus_controller.rb
require 'uri'
class KartusController < ApplicationController
  before_action :set_kartu, only: [:show, :edit, :update, :destroy]

  # GET /kartus
  # GET /kartus.json
  def index
    @kartus = Kartu.all
  end

  # GET /kartus/1
  # GET /kartus/1.json
  def show
  end

  def show_saldo
    @kartu = Kartu.find_by_nomor(params[:nomor])
  end

  def xsc
    @kartu = Kartu.find_by_nomor(params[:nomor])
    respond_to do |format|
      if @kartu.update(kartu_params)
        @sisa_saldo = @kartu.saldo
        # format.html { redirect_to kartus_url, notice: 'Kartu was successfully updated.' }
        format.json { render :show, status: :ok, location: @kartu }
        # format.js
      else
        format.html { render :edit }
        format.json { render json: @kartu.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_saldo
    @kartu = Kartu.find_by_nomor(params[:nomor])
    sal = @kartu.saldo + params[:saldo]
    respond_to do |format|
      if @kartu.update(saldo: sal)
        @sisa_saldo = @kartu.saldo
        # format.html { redirect_to kartus_url, notice: 'Kartu was successfully updated.' }
        format.json { render :show, status: :ok, location: @kartu }
        # format.js
      else
        format.html { render :edit }
        format.json { render json: @kartu.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /kartus/new
  def new
    @kartu = Kartu.new
  end

  # GET /kartus/1/edit
  def edit
  end

  # POST /kartus
  # POST /kartus.json
  def create
    @kartu = Kartu.new(kartu_params)

    respond_to do |format|
      if @kartu.save
        format.html { redirect_to @kartu, notice: 'Kartu was successfully created.' }
        format.json { render :show, status: :created, location: @kartu }
      else
        format.html { render :new }
        format.json { render json: @kartu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kartus/1
  # PATCH/PUT /kartus/1.json
  def update
    respond_to do |format|
      if @kartu.update(kartu_params)
        format.html { redirect_to @kartu, notice: 'Kartu was successfully updated.' }
        format.json { render :show, status: :ok, location: @kartu }
      else
        format.html { render :edit }
        format.json { render json: @kartu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kartus/1
  # DELETE /kartus/1.json
  def destroy
    @kartu.destroy
    respond_to do |format|
      format.html { redirect_to kartus_url, notice: 'Kartu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kartu
      @kartu = Kartu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kartu_params
      params.require(:kartu).permit(:nomor, :saldo, :bonus, :freegame, :eticket)
    end
end

app/helpers/kartus_helper.rb
module KartusHelper
end

app/views/kartus/_form.html.erb
<%= form_for(@kartu) do |f| %>
  <% if @kartu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kartu.errors.count, "error") %> prohibited this kartu from being saved:</h2>

      <ul>
      <% @kartu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nomor %><br>
    <%= f.text_field :nomor %>
  </div>
   <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
   <div class="field">
    <%= f.label :bonus %><br>
    <%= f.text_field :bonus %>
  </div>
   <div class="field">
    <%= f.label :freegame %><br>
    <%= f.text_field :freegame %>
  </div>
   <div class="field">
    <%= f.label :eticket %><br>
    <%= f.text_field :eticket %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kartus/edit.html.erb
<h1>Editing kartu</h1>

<%= render 'form' %>

<%= link_to 'Show', @kartu %> |
<%= link_to 'Back', root_path %>

app/views/kartus/index.html.erb
<h1>Listing kartus</h1>

<table>
  <thead>
    <tr>
      <th>Nomor</th>
      <th>Saldo</th>
      <th>Bonus</th>
      <th>Freegame</th>
      <th>Eticket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kartus.each do |kartu| %>
      <tr>
        <td><%= kartu.nomor %></td>
        <td id="current_saldo"><%= kartu.saldo %></td>
        <td><%= kartu.bonus %></td>
        <td><%= kartu.freegame %></td>
        <td><%= kartu.eticket %></td>
        <td><%= link_to 'Show', kartu %></td>
        <td><%= link_to 'Edit', edit_kartu_path(kartu) %></td>
        <td><%= link_to 'Destroy', kartu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kartu', new_kartu_path %>

app/views/kartus/new.html.erb
<h1>New kartu</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/kartus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Nomor:</strong>
	<%= @kartu.nomor %>
	<%= @kartu.saldo %>
	<%= @kartu.bonus %>
	<%= @kartu.freegame %>
	<%= @kartu.eticket %>
</p>

<%= link_to 'Edit', edit_kartu_path(@kartu) %> |
<%= link_to 'Back', root_path %>

app/views/kartus/show_saldo.html.erb
<p id="notice"><%= notice %></p>


	<strong>Nomor:</strong>
	<%= @kartu.nomor %>
	<strong>Saldo:</strong>
	<%= @kartu.saldo %>
	<strong>Bonus:</strong>
	<%= @kartu.bonus %>
	<strong>Freegame:</strong>
	<%= @kartu.freegame %>
	<strong>Eticket:</strong>
	<%= @kartu.eticket %>


<%= link_to 'Edit', edit_kartu_path(@kartu) %> |
<%= link_to 'Back', root_path %>