config/routes.rb
Rails.application.routes.draw do

  get 'xgc/:address/:nomor' => 'events#xgc'  

  resources :kartus
  get 'saldo/:nomor' => 'kartus#show_saldo' , as: :show_saldo
  put 'xsc/:nomor' => 'kartus#xsc' , as: :xsc
  put 'add_saldo/:nomor' => 'kartus#add_saldo' 

  resources :games
  put 'games/:id/:address' => 'games#set_game_mac' , as: :set_game_mac

  resources :macs
  get 'get_game_id/:address' => 'macs#get_id' 

  root 'pages#main'

end

app/views/pages/main.html.erb
<h1>FUNREST</h1>
<h2 id="test"></h2>
<table>
  <thead>
    <tr>
      <th>Nomor</th>
      <th>Saldo</th>
      <th>Bonus</th>
      <th>Freegame</th>
      <th>Eticket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kartus.each_with_index do |kartu, index| %>
    <tr>
      <td><%= kartu.nomor %></td>
      <td id="saldo_<%= index %>"><%= kartu.saldo %></td>
      <td><%= kartu.bonus %></td>
      <td><%= kartu.freegame %></td>
      <td><%= kartu.eticket %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br><br><br>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Price-1</th>
      <th>Price-2</th>
      <th>Price-3</th>
      <th>Price-4</th>
      <th>Xbee-Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.price1 %></td>
      <td><%= game.price2 %></td>
      <td><%= game.price3 %></td>
      <td><%= game.price4 %></td>
      <% if game.mac != nil %>
      <td><%= game.mac.address %></td>
      <% elsif game.mac == nil and game.name != "coin dispenser"%>
      <td> - </td>
      <% else %>
      <td> dedicated </td>
      <% end %>
      <td><%= link_to 'Show', game, :class => "Link"  %></td>
      <td><%= link_to 'Edit', edit_game_path(game), :class => "Link"  %></td>
      <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, :class => "Link"  %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Game', new_game_path, :class => "Link" %>


<br><br><br>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Game_Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @macs.each do |mac| %>
    <tr>
      <td><%= mac.address %></td>
      <% if mac.game != nil %>
      <td><%= mac.game.name %></td>
      <td></td>
      <td></td>
      <td></td>
      <%else%>
      <td> Not Set </td>
      <td></td>
     <td><%= link_to 'Edit', edit_mac_path(mac), :class => "Link"  %></td>
      <td><%= link_to 'Destroy', mac, method: :delete, data: { confirm: 'Are you sure?' }, :class => "Link"  %></td>
      <td>Available Game: <% available = 0 %>
                          <%@games.each do|game|%>
                            <%if game.mac == nil and game.name != "coin dispenser"%>
                              <%=link_to game.name, set_game_mac_path(game,mac), method: :put, :class => "Link"  %>
                              , 
                              <% available += 1 %>
                            <% end %> 
                          <% end %>

                          <% if available == 0 %> 
                            no game available,
                            <%=link_to " CREATE ONE?", new_game_path, :class => "Link"  %> 
                          <% end %>
     </td>
     <% end %>

   </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Mac', new_mac_path %>

<%= javascript_tag do %>

$(document).ready(function(){

  updater = setInterval(updateAllSaldo, 3000);//update saldo kartu every 3 sec

  $('.Link').click( function() 
    { 
      clearInterval(updater);//clear the hanging ajax when click the link
    } 
  );

});

function updateAllSaldo() {
$.ajax({
url: 'kartus.json',
dataType: 'json',
success: function(data)
{
  for (i = 0; i < data.length; i++) { 
  $('#'+'saldo_'+i).html(data[i].saldo);
}
}
});
}


<% end %>